### ISSUE TITLE
请问这个要怎么部署在linux上

### ISSUE THREAD

**Issue by Jiwenzhen** [xiebruce/RedisWebManager#1]
请问这个要怎么部署在linux上

**Comment by xiebruce** [comment]
@Jiwenzhen 配置nginx呀，我文档有写nginx配置(在Nginx Config里)，其实就是当一个网站部署，我整个配置过程都写了，请仔细看完整个文档！

**Comment by Jiwenzhen** [comment]
嗯，文档看过了。不是太明白。把工程拉下来不需要部署一下吗？nginx代理的话也需要一个可以访问的地址吧。

**Comment by Jiwenzhen** [comment]
我看教程里面安装的部分只给了一个git拉取的命令，没有部署的过程。

**Comment by xiebruce** [comment]
@Jiwenzhen 再往下有一个nginx配置，就是用nginx配置一个网站，我这个工具就相当于一个网站，只要把源码下载下来，再用nginx配置一个vhost即可访问：
![image](https://user-images.githubusercontent.com/13575500/55133680-73eb7880-5161-11e9-9122-f8f90e1a1db7.png)

nginx配置了网站，你就访问你配置的网站地址就可以使用这个工具了，你在本地部署可以，在线上部署也可以，nginx配置网站当然要一个域名才能访问呀，除非你没用nginx部署过网站，不然这个你不可能不知道吧？

**Comment by Jiwenzhen** [comment]
哦哦，好的，谢谢。我刚接触这些，不太懂。

**Comment by xiebruce** [comment]
没事，慢慢来，另外，你看的应该是中文文档(也就是我博客)吧？其实你直接在博客下边评论也行，不需要在github上提issue，因为这个不属于issue。

**Comment by Jiwenzhen** [comment]
哦哦，好，那我关了这个。
